### ISSUE TITLE
After being in a room for about an hour, I receive a message saying that I've left it

### ISSUE THREAD

**Issue by toothrot** [blakesmith/flamethrower#5]
```
14:09 -!- Irssi: #room_name: Total of 13 nicks [1 ops, 0 halfops, 0 voices, 12 normal
15:10 -!- Alex [Alex@campfirenow.com] has left #room_name
```

Afterwords, in some rooms i can no longer send messages.

**Comment by blakesmith** [comment]
Can you try pulling the 'without_threads' branch and see if this still happens? I switched the room threads to use EM#add_periodic_timer. I'd like to figure out if this is happening because of a thread dying, or because of some other issue (maybe the streaming API dropping off). Switching to a periodic timer has some ramifications:
- Any non-streaming API request will block on the main EM thread. There's no timeout time on these, so things may get hairy if a non-streaming API call fails.
- Once all blocking Net::HTTP requests are moved to using EM::HttpRequest, this shouldn't be an issue.

Thoughts?

**Comment by blakesmith** [comment]
Turns out this was due to lack of activity on the API for the room. Should be fixed by [this commit](https://github.com/blakesmith/flamethrower/commit/6d2d099dacdab9f7242f27d5d0260ec81c7b5bbf) which will make an API call for the room info every 10 minutes which should prevent you from being booted. Give it a whirl and let me know!
